apiVersion: v1
kind: ConfigMap
metadata:
  name: my-sample-config-map
data:
  listenPort: "8080"
  imageName: my-sample-app
  imageTag: build_test
  environment: LAPTOP
  pingService: http://my-sample-app/ping
  dnsTestHosts: google.com,apple.com