---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-sample-app
  namespace: my-sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-sample-app
  revisionHistoryLimit: 3
  template:
    metadata:
      labels:
        app: my-sample-app
    spec:
      containers:
      - name: my-sample-app
        image: my-sample-app:build_test
        ports:
        - containerPort: 8080
        readinessProbe:
          tcpSocket:
            port: 8080
        livenessProbe:
          tcpSocket:
            port: 8080
        resources:
          requests: 
            memory: "50M"
            cpu: ".1"
          limits:
            memory: "50M"
            cpu: ".1"
        envFrom:
        - configMapRef: 
            name: my-sample-config-map
        env:
        - name: secret
          valueFrom:
            secretKeyRef:
              name: my-sample-app
              key: password

---
apiVersion: v1
kind: Service
metadata:
  name: my-sample-app
  namespace: my-sample-app
spec:
  selector:
    app: my-sample-app
  ports:
  - port: 80
    targetPort: 8080
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-sample-app
  namespace: my-sample-app
spec:
  rules:
  - host: my-sample-app.k8s.toddelewis.net
    http:
      paths:
      - backend:
          serviceName: my-sample-app
          servicePort: 80
